[project]
name = "mcp-apple-notes"
version = "0.1.1"
description = "MCP server for Apple Notes integration using AppleScript"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Henil C Alagiya", email = "henilcalagiya@gmail.com"}
]
maintainers = [
    {name = "Henil C Alagiya", email = "henilcalagiya@gmail.com"}
]
keywords = ["mcp", "apple-notes", "applescript", "llm", "ai", "automation"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
]
dependencies = [
    "mcp[cli]>=1.12.4",
    "pydantic>=2.0.0",
    "typing-extensions>=4.0.0",
    "aiofiles>=23.0.0",
    "rich>=13.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0"
]

[project.urls]
Homepage = "https://github.com/henilcalagiya/mcp-apple-notes"
Documentation = "https://github.com/henilcalagiya/mcp-apple-notes#readme"
Repository = "https://github.com/henilcalagiya/mcp-apple-notes"
Issues = "https://github.com/henilcalagiya/mcp-apple-notes/issues"
Changelog = "https://github.com/henilcalagiya/mcp-apple-notes/releases"

[project.scripts]
mcp-apple-notes = "mcp_apple_notes.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mcp_apple_notes"]

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.ruff]
target-version = "py310"
line-length = 88
select = ["E", "F", "I", "N", "W", "B", "C4", "UP"]
ignore = ["E501", "B008", "C901"]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "build>=1.3.0",
    "isort>=6.0.1",
    "mypy>=1.17.1",
    "ruff>=0.12.8",
    "twine>=6.1.0",
]
